const http = require('http')

const port = 3300

const server = http.createServer((req,res)=>{
    res.statusCode = 200;
    res.setHeader("Content-Type","text/html");
    res.end(`
    <h1>hello world</h1>
    <p>This page is generated by the node js server</p>
    <h2>let's try to read a html file parse it as a string and then generate it here</h2>
    `);
});
server.listen(port, () => {
    console.log(`Server running at port ${port}`)
  })